# Generated by Django 5.2.8 on 2025-12-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1Discopro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('anulado', 'Anulado'), ('en ruta', 'En ruta')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
