# Generated by Django 5.2.8 on 2025-12-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1Discopro', '0002_alter_movimiento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='numero_despacho',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Despacho (Cruz Verde)'),
        ),
    ]
