# Generated by Django 5.2.8 on 2025-12-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1Discopro', '0003_alter_movimiento_numero_despacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionmoto',
            name='estado',
            field=models.CharField(choices=[('ASIGNADA', 'Asignada'), ('FINALIZADA', 'Finalizada')], default='ASIGNADA', max_length=20),
        ),
    ]
